apiVersion: apps/v1
kind: Deployment
metadata:
  name: gossip-world-db
  namespace: gossip-world
  labels:
    app: gossip-world-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gossip-world-db
  template:
    metadata:
      labels:
        app: gossip-world-db
    spec:
      volumes:
        - name: gossip-world-db-volume
      containers:
        - name: gossip-world-db
          image: mariadb:10.6.3
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gossip-world-db-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: gossip-world-db-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: gossip-world-db-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gossip-world-db-secret
                  key: MYSQL_PASSWORD